site_name: Sailowtech-CTD Documentation
theme:
  name: material
plugins:
- awesome-pages:
- mkdocstrings:
    handlers:
      python:
        options:
          annotations_path: brief
          docstring_style: sphinx
        paths: [software]