device: Sailowtech CTD
sensors:
  dissolved-oxygen:
    name: "Dissolved Oxygen"
    address: 0x61
    sensor-type: "DISSOLVED_OXY"
  conductivity:
    name: "Conductivity Probe"
    address: 0x64
    sensor-type: "CONDUCTIVITY"
  temperature-do:
    name: "Temperature from Dissolved Oxygen Sensor"
    address: 0x66
    sensor-type: "DISSOLVED_OXY_TEMP"
  depth:
    name: "Depth Sensor"
    address: 0x76
    sensor-type: "BAR30_DEPTH"
measurements-interval: 1 # seconds
write-sql: true
