device: Sailowtech CTD
sensors:
  mock-sensor1:
    name: "Mock Sensor 1"
    address: 0x42
    sensor-type: "MOCK_SENSOR"
    min: 0.1
    max: 5
  mock-sensor2:
    name: "Mock Sensor 2"
    address: 0x43
    sensor-type: "MOCK_SENSOR"
    min: 0.1
    max: 10
interval: 1 # seconds
mock: true
