name: Build Raspberry PI Image

on:
  push:
    branches:
      - image-build

jobs:
  build-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install dependencies for pi-gen
        run: sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc gpg pigz xxd arch-test
      - name: Checkout pi-gen repository
        uses: actions/checkout@v4
        with:
          repository: RPi-Distro/pi-gen
          path: pi-gen
          ref: arm64
          submodules: true
      - name: Add config to skip stages that are not required
        run: touch pi-gen/stage3/SKIP pi-gen/stage4/SKIP pi-gen/stage5/SKIP pi-gen/stage4/SKIP_IMAGES pi-gen/stage5/SKIP_IMAGES
      - name: Add config to not export stage2 as image
        run: rm pi-gen/stage2/EXPORT_IMAGE
      - name: Make ctd-stage scripts executable
        run: chmod +x os/ctd-stage/00-install-ctd-software/00-run-chroot.sh os/ctd-stage/01-setup-networks/00-run-chroot.sh os/ctd-stage/prerun.sh
      - name: List files
        run: tree
      - name: Build the Image
        run: sudo pi-gen/build.sh -c os/config
      - name: Upload the built image as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sailowtech-ctd-rpi-image
          if-no-files-found: error
          overwrite: true
          path: pi-gen/deploy/*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: pi-gen/deploy/*