name: Build Raspberry PI Image

on:
  push:
    branches:
      - image-build

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install dependencies for pi-gen
        run: sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc gpg pigz xxd arch-test
      - name: Checkout pi-gen repository
        uses: actions/checkout@v4
        with:
          repository: RPi-Distro/pi-gen
          path: pi-gen
          ref: arm64
          submodules: true
      - name: Skip stages that are not required
        run: touch pi-gen/stage3/SKIP pi-gen/stage4/SKIP pi-gen/stage5/SKIP pi-gen/stage4/SKIP_IMAGES pi-gen/stage5/SKIP_IMAGES
      - name: Build the Image
        run: pi-gen/build.sh -c os/config
      - name: List files
        run: ls -la pi-gen/deploy; tree